monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output.usb-C-Media_Electronics_Inc.*"
      }
    ]
    actions = {
      update-props = {
          api.alsa.headroom = 1024
      }
    }
  }
]
