"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color9)\
$os\
$username\
[](bg:color7 fg:color9)\
$directory\
[](fg:color7 bg:color11)\
$git_branch\
$git_status\
[](fg:color11 bg:color10)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color10 bg:color4)\
$docker_context\
[](fg:color4 bg:color14)\
$time\
[ ](fg:color14)\
$line_break$character"""

palette = 'pywal'

[palettes.pywal]
color0 = "black"
color1 = "red"
color2 = "green"
color3 = "yellow"
color4 = "blue"
color5 = "magenta"
color6 = "cyan"
color7 = "white"
color8 = "bright-black"
color9 = "bright-red"
color10 = "bright-green"
color11 = "bright-yellow"
color12 = "bright-blue"
color13 = "bright-magenta"
color14 = "bright-cyan"
color15 = "bright-white"

[os]
disabled = false
style = "bg:color9 fg:color0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bold bg:color9 fg:color0"
style_root = "bold bg:color9 fg:color0"
format = '[ $user ]($style)'

[directory]
style = "fg:color0 bg:color7"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color6 fg:color0"
format = '[[ $symbol $branch ](fg:color0 bg:color11)]($style)'

[git_status]
style = "bg:color6 fg:color0"
format = '[[ ($all_status $ahead_behind) ](fg:color0 bg:color11)]($style)'

[nodejs]
symbol = ""
style = "bg:color6"
format = '[[ $symbol( $version) ](fg:color0 bg:color10)]($style)'

[c]
symbol = " "
style = "bg:color6"
format = '[[ $symbol( $version) ](fg:color0 bg:color10)]($style)'

[rust]
symbol = ""
style = "bg:color6"
format = '[[ $symbol( $version) ](fg:color0 bg:color10)]($style)'

[golang]
symbol = ""
style = "bg:color6"
format = '[[ $symbol( $version) ](fg:color0 bg:color10)]($style)'

[php]
symbol = ""
style = "bg:color6"
format = '[[ $symbol( $version) ](fg:color0 bg:color10)]($style)'

[java]
symbol = " "
style = "bg:color6"
format = '[[ $symbol( $version) ](fg:color0 bg:color10)]($style)'

[kotlin]
symbol = ""
style = "bg:color6"
format = '[[ $symbol( $version) ](fg:color0 bg:color10)]($style)'

[haskell]
symbol = ""
style = "bg:color6"
format = '[[ $symbol( $version) ](fg:color0 bg:color10)]($style)'

[python]
symbol = ""
style = "bg:color6"
format = '[[ $symbol( $version) ](fg:color0 bg:color10)]($style)'

[docker_context]
symbol = ""
style = "bg:color10"
format = '[[ $symbol( $context) ](fg:color0 bg:color3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color14"
format = '[[  $time ](fg:color0 bg:color14)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color5)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:color5)'
vimcmd_replace_one_symbol = '[](bold fg:color5)'
vimcmd_replace_symbol = '[](bold fg:color5)'
vimcmd_visual_symbol = '[](bold fg:color9)'
