preload = /home/tristan/Documents/wallpapers/nature2/natural-background-yucca-leaves-close-up-selective-focus-tropical-park-blue-green-yucca-leaves-horizontal-shot.jpg
wallpaper = , /home/tristan/Documents/wallpapers/nature2/natural-background-yucca-leaves-close-up-selective-focus-tropical-park-blue-green-yucca-leaves-horizontal-shot.jpg
