source = /home/$USER/.cache/wal/colors-hyprland

background {
    monitor =
    path = $wallpaper
    blur_size = 3
    blur_passes = 3
    brightness = .6
    reload_time = 1
}

input-field {
    monitor = eDP-1
    size = 13%, 4%
    outline_thickness = 0
    dots_rounding = 4
    dots_spacing = .5
    dots_fase_time = 300
    inner_color = $backgroundCol
    outer_color = $backgroundCol $backgroundCol
    check_color= $backgroundCol $backgroundCol
    fail_color= $backgroundCol $backgroundCol
    font_color = $color9
    font_family = ProFontWindows Nerd Font
    fade_on_empty = false
    shadow_color = rgba(0,0,0,0.5)
    shadow_passes = 2
    shadow_size = 4
    blur_size = 5
    blur_passes = 1
    rounding = 20
    placeholder_text = <i></i>
    fail_text = <b>FAIL</b>
    fail_timeout = 250
    position = 0, -100
    halign = center
    valign = center
}

# now playing
label {
	monitor = DP-7
	text = cmd[update:500] cat /home/tristan/.cache/hyprlock/musicdata.txt
	color = $color4
	font_size = 24
	font_family = ProFontWindows Nerd Font Bold
	shadow_passes = 0
	shadow_size = 4
	position = 0,-200
	halign = center
	valign = center
}

# album art
image {
    monitor = DP-7
	path = /home/tristan/.cache/hyprlock/albumart.png
	size = 600
	position = 0,150
	halign = center
	valign = center
	rounding = 5
	shadow_passes = 2
	shadow_size = 1
	shadow_color = rgba(0,0,0,0.5)
	reload_time = 1
	border_size = 0
}

# hours
label {
    monitor = eDP-1
    text = cmd[update:1000] date +"<b>%I</b>"
    color = $color9
    font_size = 220
    font_family = ProFontWindows Nerd Font
    shadow_passes = 0
    shadow_size = 5
    position = -100, 350
    halign = center
    valign = center
}

# minutes
label {
    monitor = eDP-1
    text = cmd[update:1000] date +"<b>%M</b>"
    color = $color6
    font_size = 220
    font_family = ProFontWindows Nerd Font
    shadow_passes = 0
    shadow_size = 5
    position = 100, 100
    halign = center
    valign = center
}

# date (bottom right)
label {
    monitor = eDP-1
    text = cmd[update:1000] date +"<b>%A, %B %d, %Y</b>"
    color = $color4
    font_size = 36
    font_family = ProFontWindows Nerd Font
    shadow_passes = 0
    shadow_size = 4
    position = -30, 20
    halign = right
    valign = bottom
}

# equalizer
label {
    monitor = DP-7
    text = cmd[update:1] ~/.config/scripts/eq.sh
    color = $color6
    font_size = 28
    font_family = MesloLGL Nerd Font
    position = 0, -250
    halign = center
    valign = center
}

# equalizer_inverted
label {
    monitor = DP-7
    text = cmd[update:1] ~/.config/scripts/eq_inverted.sh
    color = $color6
    font_size = 28
    font_family = MesloLGL Nerd Font
    position = 0, -280
    halign = center
    valign = center
}

# suspend
label {
    monitor = eDP-1
    text = <span> 󰾉 </span>
    reload_time = 1
    halign = left
    valign = bottom
    position = 200, 12
    font_size = 60
    color = $color4
    onclick = systemctl suspend
}

# power off
label {
    monitor = eDP-1
    text = <span>  </span>
    reload_time = 1
    halign = left
    valign = bottom
    position = 0, 20
    font_size = 52
    color = $color4
    onclick = systemctl poweroff || loginctl poweroff
}

# reboot
label {
    monitor = eDP-1
    text = <span> 󰜉 </span>
    reload_time = 1
    halign = left
    valign = bottom
    position = 96, 14
    font_size = 64
    color = $color4
    onclick = systemctl reboot || loginctl reboot
}
