preload = /home/tristan/Documents/wallpapers/landscape_pond_trees_clouds_mountains_reflection_water_landscape_wallpaper_background_4k_hd_nature.jpg
wallpaper = , /home/tristan/Documents/wallpapers/landscape_pond_trees_clouds_mountains_reflection_water_landscape_wallpaper_background_4k_hd_nature.jpg
