preload = /home/tristan/Documents/wallpapers/abstract/wallpapersden.com_abstract-wave-grey-duotone_2560x1435.jpg
wallpaper = , /home/tristan/Documents/wallpapers/abstract/wallpapersden.com_abstract-wave-grey-duotone_2560x1435.jpg
