hl.workspace_rule({ workspace = "1", monitor = "eDP-1"})
hl.workspace_rule({ workspace = "2", monitor = "eDP-1"})
hl.workspace_rule({ workspace = "3", monitor = "eDP-1"})
hl.workspace_rule({ workspace = "4", monitor = "eDP-1"})
hl.workspace_rule({ workspace = "5", monitor = "eDP-1"})
hl.workspace_rule({ workspace = "6", monitor = "desc:HP Inc. HP Z27 CN49270NPK"})
hl.workspace_rule({ workspace = "7", monitor = "desc:HP Inc. HP Z27 CN49270NPK"})
hl.workspace_rule({ workspace = "8", monitor = "desc:HP Inc. HP Z27 CN49270NPK"})
hl.workspace_rule({ workspace = "9", monitor = "desc:Lenovo Group Limited T24-40 V5WNM516"})
hl.workspace_rule({ workspace = "10", monitor = "desc:Lenovo Group Limited T24-40 V5WNM516"})
